Repository anyname-space/anyname, pull requests merged in 2024-09, with the labels that each got.

#2 add .gitignore
  .gitignore
Labels: hacktoberfest

#20 Unit test 1
  data/names/1/mekhaha.json
  data/names/1/ronaldo.json
Labels: hacktoberfest

#40 add 3
  data/names/1/test3.json
Labels: hacktoberfest, opened

#49 Add test 11
  .github/workflows/validator_name.yml
  data/names/1/test-11.json
  validator/validate_name.go
Labels: invalid, hacktoberfest, opened

#50 add validator: name, category
  $GITHUB_OUTPUT
  .github/workflows/validator.yml
  validator/go.mod
  validator/main.go
  validator/validate_category.go
  validator/validate_name.go
Labels: hacktoberfest, opened

#52 Add validate duplicate
  $GITHUB_OUTPUT
  .github/workflows/validate-duplicate.yml
  data/names/1/test-12-1.json
  data/names/1/test12.json
  validator/main.go
  validator/validate-duplicate/go.mod
  validator/validate-duplicate/validate-duplicate.go
Labels: invalid, hacktoberfest, opened
